# 2 Layers Neural Network

In [20]:
from numpy import *

In [37]:
x = array([(0, 0, 1), 
           (0, 1, 1), 
           (1, 0, 1), 
           (1, 1, 1)])

y = array([(0), (1), (1), (0)])

In [39]:
def sigmoid(x, deriv=False):
    if deriv == True:
        return sigmoid(x) * (1 - sigmoid(x))
    else:
        return exp(x) / (exp(x) + 1)

In [47]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = array([(0.5, 0.5, 1.5, 1.5), 
                               (0.5, 1.5, 1.5, 1.4), 
                               (1.5, 0.5, 1.5, 0.4)])
        
        self.weights2 = random.rand(4,4)
        self.y = y
        self.output = zeros(y.shape)
    
    ''' The output of a 2 layer NN with sigmoid function as activation, 
        will be Y = sigm(W2 * sigm(W1 * x + b1) + b2)'''
    
    def feedforward(self):
        self.layer1 = sigmoid(dot(self.input, self.weights1))
        self.output = sigmoid(dot(self.layer1, self.weights2))
        
    def backprop(self):
        d_weights2 = dot(self.layer1.T, (2*(self.y - self.output) * sigmoid(self.output, deriv=True)))
        d_weights1 = dot(self.input.T,  (dot(2*(self.y - self.output) * sigmoid(self.output, deriv=True), self.weights2.T) * sigmoid(self.layer1, deriv=True)))

        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [58]:
step = 200
nn = NeuralNetwork(x, y)

for i in range(0, step):
    nn.feedforward()
    nn.backprop()
    print(nn.weights1, nn.weights2)
    print()
    print((nn.y - nn.output))
    print()

[[0.47990945 0.33094716 1.49015846 1.40675311]
 [0.47907155 1.33441017 1.48964092 1.30569122]
 [1.46817522 0.1629905  1.48453429 0.21204174]] [[-0.79335938  1.05121186  1.21721677 -1.00507825]
 [-0.52552034  0.37605626  0.37706252 -0.32939226]
 [-1.21045533  0.62497799  0.92917883 -0.98264346]
 [-0.59112766  0.69171792  0.29950346 -0.79028495]]

[[-0.7165267   0.26497385  0.17346854 -0.72517537]
 [-0.77117202  0.23050224  0.14289669 -0.7825955 ]
 [-0.75825823  0.23125654  0.14614062 -0.76425613]
 [-0.78691384  0.21665807  0.132555   -0.79590861]]

[[0.53034464 0.35205235 1.53455244 1.43622503]
 [0.52773278 1.35396207 1.5323983  1.33420577]
 [1.58662492 0.21272488 1.59030054 0.28414208]] [[-0.90978994  1.18181233  1.33360129 -1.12243932]
 [-0.61750238  0.47966936  0.46970522 -0.42223032]
 [-1.33349623  0.76311957  1.05239467 -1.106665  ]
 [-0.69291452  0.80638134  0.40214677 -0.89287402]]

[[-0.0959925   0.12459378  0.10752459 -0.09682756]
 [-0.05951213  0.08399825  0.07564521 -0.061120

 [-1.51702483  1.64740759  1.22838339 -1.71674342]]

[[-0.00232339  0.00293487  0.00283234 -0.0023231 ]
 [-0.00113277  0.00145899  0.00149709 -0.00114282]
 [-0.00128026  0.00162814  0.00167063 -0.00126587]
 [-0.00097515  0.00125397  0.00130688 -0.00098025]]

[[1.04661259 0.64574284 2.02338139 1.79312533]
 [1.01333941 1.62111208 1.99175466 1.67030008]
 [2.89315003 0.96537339 2.83626906 1.22220369]] [[-1.8482276   2.13810268  2.26841546 -2.06077069]
 [-1.37623806  1.25396998  1.23020649 -1.1813547 ]
 [-2.29094558  1.73924826  2.00687459 -2.06398624]
 [-1.51952272  1.64991427  1.23090958 -1.71924165]]

[[-0.00229644  0.00290092  0.00279994 -0.00229613]
 [-0.00112022  0.00144277  0.00148047 -0.00113014]
 [-0.00126584  0.00160982  0.00165185 -0.00125168]
 [-0.00096469  0.00124049  0.00129278 -0.00096976]]

[[1.04844764 0.64690164 2.02515955 1.79448207]
 [1.0150663  1.62217705 1.99342729 1.67157793]
 [2.89779121 0.96835191 2.84077937 1.22573969]] [[-1.85093391  2.14081692  2.27114321 -2.0634

[[1.17161286 0.72570434 2.14477043 1.88642052]
 [1.13136409 1.69502168 2.10632708 1.75845645]
 [3.20632093 1.16901554 3.14112544 1.46251469]] [[-2.0246409   2.31500871  2.44645022 -2.23725872]
 [-1.52939517  1.40765625  1.38527675 -1.3346242 ]
 [-2.46803177  1.91683429  2.18562057 -2.24114733]
 [-1.68200926  1.81293349  1.39536663 -1.88180677]]

[[-0.00107074  0.00135518  0.00131791 -0.00107024]
 [-0.00054587  0.00070149  0.00071966 -0.00055023]
 [-0.00060839  0.00077406  0.00079413 -0.00060356]
 [-0.00048156  0.00061825  0.00064176 -0.00048442]]

[[1.1725887  0.72633626 2.14571994 1.88715547]
 [1.13228882 1.69560925 2.10722657 1.75915337]
 [3.20874038 1.1706084  3.14348428 1.46438387]] [[-2.02595779  2.31632915  2.4477806  -2.23857656]
 [-1.5305542   1.40881905  1.38645093 -1.33578439]
 [-2.46935245  1.91815856  2.18695495 -2.24246896]
 [-1.68323285  1.81416086  1.39660574 -1.88303134]]

[[-0.00106458  0.0013474   0.00131042 -0.00106408]
 [-0.00054295  0.00069772  0.00071579 -0.000547